version: "3.8"
services:
  modidock:
    build:
      context: /opt/docker/volumes/modidock
      dockerfile: Dockerfile
    container_name: modidock
    ports:
      - 7000:8080
    environment:
      - NODE_ENV=production
      - VOLUME_ROOT=/volumes
    volumes:
      # 1) Docker socket (so Modidock can restart other containers)
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/volumes/modidock/config:/app/config:ro
    restart: unless-stopped
networks: {}
